universe        = vanilla
executable      = run_hdlm.sh
getenv          = True

request_gpus    = 8
request_cpus    = 32
request_memory  = 192GB

# Force A100 80GB
requirements    = regexp("H100", TARGET.GPUs_DeviceName) && (TARGET.GPUs_GlobalMemoryMb >= 80000)

+MaxRuntime = 43200 

output          = logs/hdlm.$(Cluster).out
error           = logs/hdlm.$(Cluster).err
log             = logs/hdlm.$(Cluster).log

queue